config/routes.rb
MyApp::Application.routes.draw do
  devise_for :admins









  resources :owners do
    resources :cars
  end
  resources :postis
  resource :search, only: :show, controller: :search
  root :to => 'owners#index'



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= Admin.new # guest user (not logged in)
       if user.admin?
         can :manage, :all

       else
         can [:create, :edit, :update], :all
         cannot :destroy, :all
    end

  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner
  attr_accessible :brand, :model, :nauto, :owner_id

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cars, :dependent => :destroy
  attr_accessible :fam, :name
end

app/models/posti.rb
class Posti < ActiveRecord::Base
  attr_accessible :actdate, :area, :autonom, :city, :city_1, :indexold, :opsname, :opssubm, :opstype, :region
  self.per_page = 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private

  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_filter :authenticate_admin!, :except => [:index]
    def index
      @post = Owner.find(params[:owner_id])
      @post_sh = @post.cars.all
    end

    def new
      @post_sh = Car.new
    end

    def create
      @post = Owner.find(params[:owner_id])
      @post_sh = @post.cars.create(params[:post_sh])
      redirect_to owner_cars_path

    end

    def edit
      @post = Owner.find(params[:owner_id])
      @post_sh = @post.cars.find(params[:id])
    end
    def update
      @post = Owner.find(params[:owner_id])
      @post_sh = @post.cars.find(params[:id])

      if @post_sh.update_attributes(params[:post_sh])
        redirect_to :action => :index
      else
        render 'edit'
      end
    end
    def destroy
      @post = Car.find(params[:id])
      @post.destroy
      redirect_to :action => :index
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index]
  def index
    @owner = Owner.all

  end

  def new
    @owner = Owner.new
  end

  def create

    @owner = Owner.new(params[:owner])

    if @owner.save
      redirect_to root_path
    else
      render 'new'
    end
    authorize! :create, @owner
  end

  def edit
    @owner = Owner.find(params[:id])
    authorize! :edit, @owner
  end
  def update

      @owner = Owner.find(params[:id])

      if @owner.update_attributes(params[:owner])
        redirect_to :action => :index
      else
        render 'edit'
      end
      authorize! :update, @owner
  end
  def destroy
    authorize! :destroy, @owner
    @owner = Owner.find(params[:id])

    @owner.destroy
    redirect_to :action => :index

  end
end

app/controllers/postis_controller.rb
class PostisController < ApplicationController
  def index
    @pos = Posti.paginate(:page => params[:page])
  end
  def show
    @pos = Posti.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @result = Posti.search params[:search], :page =>params[:page], per_page: 20
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/postis_helper.rb
module PostisHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cars/_form.html.haml
= form_for @post do |f|
  %p
    = f.label 'Марка'
    = f.text_field :brand
  %p
    = f.label 'Модель'
    = f.text_field :model
  %p
    = f.label 'Номер авто'
    = f.text_field :nauto
  %p
    = f.submit

app/views/cars/edit.html.haml
%h1 Редактирование данных машины
= form_for :post_sh, :url => { :action => :update }, :method => :put do |f|
  %p
    = f.label 'Марка'
    = f.text_field :brand
  %p
    = f.label 'Модель'
    = f.text_field :model
  %p
    = f.label 'Номер авто'
    = f.text_field :nauto
  %p
    = f.submit 'Обновить данные', {:class => 'btn btn-primary'}
= link_to 'К списку машин владельца', :action => :index

app/views/cars/index.html.haml
%h1Машины: #{@post.fam} #{@post.name}

%table.table.table-hover
  %tr
    %th Марка
    %th Модель
    %th Номер авто


  - @post_sh.each do |post|
    %tr
      %td= post.brand
      %td= post.model
      %td= post.nauto
      %td= link_to 'Редактировать', :action => :edit, :id => post.id
      %td= link_to 'Удалить', {:action => :destroy, :id => post.id}, :method => :delete, :confirm => 'Вы уверены?'


%p= link_to 'Добавить машину', :action => :new
%p= link_to 'К списку владельцев', :controller => :owners, :action => :index

app/views/cars/new.html.haml
= form_for :post_sh, :url => { :action => :create } do |f|
    - if @post_sh.errors.any?
        %div#errorExplanation
            %h2 "#{pluralize(@post.errors.count, 'error')}" prohibited this post from being saved:
            %ul
                - @post_sh.errors.full_messages.each do |msg|
                    %li= msg
    %p
        = f.label 'Марка'
        = f.text_field :brand
    %p
        = f.label 'Модель'
        = f.text_field :model
    %p
        = f.label 'Номер авто'
        = f.text_field :nauto
    %p
        = f.submit "Добавить машину", {:class => 'btn btn-primary'}
= link_to 'Назад', :action => :index

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title MyApp
  = stylesheet_link_tag    'application', :media => 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  .container-fluid
    .row-fluid.header
      .row-fluid
        .span4.offset6
          = form_tag(search_path, :method =>  :get, class: 'navbar-search')  do
            = text_field_tag :search, params[:search], :class => 'span12 search-query', :placeholder => 'Поиск'
          .btn-group.pull-right
            =link_to 'Вход', new_admin_session_path, class: 'btn'
            =link_to 'Регистрация', new_admin_registration_path, class: 'btn btn-primary'
      .row-fluid
        .span2.offset2
          .wrap
            =link_to 'Post Land', root_path
      .row-fluid
        .span8.offset2
          .navbar.navbar-inverse
            .navbar-inner
              %ul.nav
                %li{:class => "#{'active' if current_page?(root_path)}"}
                  =link_to 'Главная', root_path
                %li{:class => "#{'active' if current_page?(postis_path)}"}
                  =link_to 'Индексы', postis_path
                -if current_page?(search_path)
                  %li.active
                    =link_to 'Результаты поиска', search_path
    .row-fluid
      .span2
      .span8= yield
      .span2
    .row-fluid

app/views/owners/_form.html.haml
= form_for @owner do |f|
  %p
    = f.label 'Фамилия'
    = f.text_field :fam
  %p
    = f.label 'Имя'
    = f.text_field :name
  %p
    = f.submit 'Добавить', {:class => 'btn btn-primary'}

app/views/owners/edit.html.haml
%h3 Редактирование данных владельца
= render 'form'
= link_to 'Назад', :action => :index

app/views/owners/index.html.haml
%h3 Список владельцев
- if admin_signed_in?
  %p Вы вошли в систему под именем: #{current_admin.email}

  = link_to 'Выйти', destroy_admin_session_path, :method => :delete
%table.table.table-hover
  %tr
    %th Фамилия
    %th Имя


  - @owner.each do |o|
    %tr
      %td= o.fam
      %td= o.name
      %td= link_to 'Добавить машину', :controller => :cars, :action => :new, :owner_id => o.id
      %td= link_to 'Показать машины владельца', :controller => :cars, :action => :index, :owner_id => o.id
      %td= link_to 'Редактировать', :action => :edit, :id => o.id
      - if can? :destroy, @owner
        %td= link_to 'Удалить', {:action => :destroy, :id => o.id}, :method => :delete, :confirm => 'Вы уверены?'



%p= link_to 'Добавить нового владельца', :action => :new
%p= link_to 'Посмотреть почтовый индекс', :controller => :postis, :action => :index

app/views/owners/new.html.haml
= render 'form'
= link_to 'Назад', :action => :index

app/views/postis/index.html.haml
%table.table.table-condensed.table-hover
  %tr>
    %th Индекс
    %th Имя опс
    %th Область
    %th Автономер
    %th Район
    %th Город
    %th Город_1

  
  -@pos.each do |p|
    %tr
      %td= p.id
      %td= p.opsname
      %td= p.region
      %td= p.autonom
      %td= p.area
      %td= p.city
      %td= p.city_1
      %td= link_to 'Show', :action => :show, :id => p.id, :page => params[:page]


= will_paginate @pos, :renderer => BootstrapPagination::Rails, :class => 'pagination pagination-mini pagination-centered'
= link_to 'На главную', root_path

app/views/postis/show.html.haml
%table.table.table-condensed.table-hover
  %tr
    %th Индекс
    %th Имя опс
    %th Тип опс
    %th Opssubm
    %th Область
    %th Автономер
    %th Район
    %th Город
    %th Город_1
  %tr
    %td= @pos.id
    %td= @pos.opsname
    %td= @pos.opstype
    %td= @pos.opssubm
    %td= @pos.region
    %td= @pos.autonom
    %td= @pos.area
    %td= @pos.city
    %td= @pos.city_1
= link_to 'Назад', :action => :index, :page => params[:page]
%br
= link_to 'На главную', root_path

app/views/search/show.html.haml
-if @result.empty?
  %h3 Вы ничего не нашли по запросу "#{params[:search]}"!
-else
  %table.table.table-condensed.table-hover
    %tr
      %th Индекс
      %th Имя опс
      %th Область
      %th Автономер
      %th Район
      %th Город
      %th Город_1


    -@result.each do |p|
      %tr
        %td= p.id
        %td= p.opsname
        %td= p.region
        %td= p.autonom
        %td= p.area
        %td= p.city
        %td= p.city_1
        %td= link_to 'Show', :controller => :postis, :action => :show, :id => p.id, :page => params[:page]
=will_paginate @result, :renderer => BootstrapPagination::Rails, :class => 'pagination pagination-mini pagination-centered'